### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by djjudas21** [david-barbion/puppet-dhcpd#5]
Hi David,

Thanks for accepting my previous merge requests. I think I am finished working on this now - please could you create a new release on Puppet Forge?

Thanks,
Jonathan

**Comment by david-barbion** [comment]
Hi Jonathan,

Thanks for all your work. Can I mention your name in the changelog?

David.

**Comment by djjudas21** [comment]
Please do :smile:

**Comment by david-barbion** [comment]
Done
