### ISSUE TITLE
Puppet4 compatible...

### ISSUE THREAD

**Issue by dominiquearpin** [david-barbion/puppet-dhcpd#8]
Hi,

I got some issue to get this module works with Puppet4.  You should not use this path directly, because I test it in our environment.

init.pp: 
# Class['dhcpd::config'] ~> Class ['dhcpd::service']

params.pp:
class dhcpd::params {
  case $::os[family] {
    'RedHat': {
      $package_name = 'dhcp'
      $service_name = 'dhcpd'
      case $::os[release][major] {
        '3','4','5': {
          $config_file  = '/etc/dhcpd.conf'
        }
        '6','7': {
          $config_file  = '/etc/dhcp/dhcpd.conf'
        }
        default: {
          fail('os version not supported')
        }
      }
    }
    default: { fail('osfamily not supported') }
  }
}
# subnet.pp

  concat::fragment { "${_shared_network_name}_2_${_subnet_name}_subnet_3":
    content => template('dhcpd/dhcpd_subnet_end.conf.erb'),
    target  => $config_file,
    order   => 11, #Change the order, the dhcp_subnet_end.conf.erb was called too early
  }

**Comment by djjudas21** [comment]
This is addressed in #9

**Comment by david-barbion** [comment]
Thanks again!
